apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: hello-world-ingress
  namespace: ingress-demo
  labels:
    name: hello-world-ingress
spec:
  tls:
    - hosts:
        - hello.myminikube.demo
      secretName: mkcert-tls-secret
  rules:
  - host: hello.myminikube.demo
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-svc
            port:
              number: 8080
